### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by debanjansen48** [martin-sicho/genui-gui#4]
Hallo Sir, I am a Linux Mint 19.3 Cinnamon user. My system is integrated with NVIDIA GPU and CUDA 11.3. Kindly guide me how to install your esteemed tool for denovo design and QSAR based prediction.
Thanks

**Comment by martin-sicho** [comment]
Hi @debanjansen48, thanks for the interest in the software. The best way to get started would probably be through docker: https://github.com/martin-sicho/genui-docker/#quick-start. 

This repo only contains the frontend part of the GenUI, but if you would like to add new features and customize things a bit more there is also documentation for the backend python package, which has instructions on how to setup your environment: https://martin-sicho.github.io/genui/docs/index.html. It is all still work in progress so far from being 'esteemed', but maybe you will find it useful :)
